function ps2q5
% ID: 1517982, Alejandro Salazar Lobos
% Solution to question 5, problem set 2

x = [21 22 23 24];
B = ones(3,3);

%C = reshape(x,2,2) % Create matrix generated by vector x
%D = C' % Create matrix equal to the transpose of C
%E = [B(1,:); D B([1,3],3)] % Put C and B into a single matrix

[B(1,:); reshape(x,2,2)' B([2,3],3)]

end

